language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
cache:
  directories:
    - ./Unity
before_install:
- chmod a+x ./Travis/installUnity.sh
install:
- ./Travis/installUnity.sh
before_script:
- chmod a+x ./Travis/createProject.sh
- chmod a+x ./Travis/installSDK.sh
- chmod a+x ./Travis/runTests.sh
- chmod a+x ./Travis/build.sh
script:
- ./Travis/createProject.sh
- ./Travis/installSDK.sh
- travis_wait 15 ./Travis/runTests.sh
- ./Travis/build.sh
